// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9DQROy5i5crhlkPvoHhUkZ6JLGeZurQ',
    appId: '1:339149447240:web:b9d8fafa240db63424f87d',
    messagingSenderId: '339149447240',
    projectId: 'foodapp-9694a',
    authDomain: 'foodapp-9694a.firebaseapp.com',
    storageBucket: 'foodapp-9694a.appspot.com',
    measurementId: 'G-PCYRMJ4ZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTKCH65MEXFR54vljY1bLwiZ33DGBeJUc',
    appId: '1:339149447240:android:c7b3fc1024f9834324f87d',
    messagingSenderId: '339149447240',
    projectId: 'foodapp-9694a',
    storageBucket: 'foodapp-9694a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM5FAs8YrbKgSE4PLEOJy7t9iYRD3OTXQ',
    appId: '1:339149447240:ios:1e5a3ad3eef8bdc524f87d',
    messagingSenderId: '339149447240',
    projectId: 'foodapp-9694a',
    storageBucket: 'foodapp-9694a.appspot.com',
    iosClientId: '339149447240-3eg3bv7o8tqa9lomhjah23tbgfunmosv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodTracker',
  );
}
